export const ACTIONS = {
  LOADING_STATUS_TRUE: "LOADING_STATUS_TRUE",
  LOADING_STATUS_FALSE: "LOADING_STATUS_FALSE",
  LOGIN_USER_REQUEST: "LOGIN_USER_REQUEST",
  LOGIN_USER_SUCCESSFUL: "LOGIN_USER_SUCCESSFUL",
  LOGIN_USER_FAILURE: "LOGIN_USER_FAILURE",
  CLEAR_ERRORS: "CLEAR_ERRORS",
  LOGOUT: "LOGOUT",
  CREATE_ERROR: "CREATE_ERROR",
  SET_CONFIGURATION: "SET_CONFIGURATION",
  SET_DATA: "SET_DATA",
  SET_DAY: "SET_DAY",
  OPEN_CONFIG: "OPEN_CONFIG",
  CLOSE_CONFIG: "CLOSE_CONFIG",
  SET_UNIVERSITIES_DATA: "SET_UNIVERSITIES_DATA"
};
