export const ACTIONS = {
  LOADING_STATUS_TRUE: "LOADING_STATUS_TRUE",
  LOADING_STATUS_FALSE: "LOADING_STATUS_FALSE",
  FETCH_IMAGES_FOR_GALLERY: "FETCH_IMAGES_FOR_GALLERY",
  FETCH_IMAGES_FOR_USER: "FETCH_IMAGES_FOR_USER",
  FETCH_COMMENTS_FOR_GALLERY: "FETCH_COMMENTS_FOR_GALLERY",
  LOGIN_USER_REQUEST: "LOGIN_USER_REQUEST",
  LOGIN_USER_SUCCESSFUL: "LOGIN_USER_SUCCESSFUL",
  LOGIN_USER_FAILURE: "LOGIN_USER_FAILURE",
  CLEAR_ERRORS: "CLEAR_ERRORS",
  LOGOUT: "LOGOUT",
  CREATE_ERROR: "CREATE_ERROR"
};

export const ERRORS = {
  EMPTY_LOGIN: "Login field cannot be empty!",
  EMPTY_PASSWORD: "Password field cannot be empty!",
  EMPTY_CONFIRM_PASSWORD: "Confirm password field cannot be empty!",
  PASSWORDS_DO_NOT_MATCH: "Passwords do not match!"
};
